services:
  - type: web
    name: mannvasam
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir backend terracotta_jewelry.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: NODE_VERSION
        value: "22.11.0"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
