# Generated by Django 6.0.2 on 2026-08-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_video', models.FileField(blank=True, help_text="MP4 used as the homepage hero background. Leave blank to use the frontend's bundled fallback.", null=True, upload_to='hero/')),
                ('hero_poster', models.ImageField(blank=True, help_text='Still image shown while the video loads (and if no video is set).', null=True, upload_to='hero/')),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
