# Generated by Django 6.0.2 on 2026-08-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='heritage_poster',
            field=models.ImageField(blank=True, help_text='Still image shown while the heritage video loads.', null=True, upload_to='heritage/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='heritage_video',
            field=models.FileField(blank=True, help_text="MP4 shown in the Heritage section's graphic tile. Leave blank to use the frontend's bundled fallback.", null=True, upload_to='heritage/'),
        ),
    ]
