# Generated by Django 6.0.2 on 2026-08-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sitesettings_heritage_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(help_text='e.g. Shape, Dry, Bisque fire.', max_length=60)),
                ('days', models.CharField(help_text="e.g. 'Day 1–2'.", max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='process/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
